# Sandrine Burriel <sandrine@bureau-cornavin.com>, 2016.
# Éric Bischoff <ebischoff@bureau-cornavin.com>, 2016.
msgid ""
msgstr ""
"Project-Id-Version: univention-lib\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2021-11-03 17:54+0100\n"
"PO-Revision-Date: 2021-12-10 12:07+0100\n"
"Last-Translator: Nicolas Sidi <nicolas.sidi@mailbox.org>\n"
"Language-Team: French <fr@bureau-cornavin.com>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: Poedit 3.0\n"

#: python/package_manager.py:1106
msgid "Autoremove failed"
msgstr "Échec de la suppression automatique"

#: python/package_manager.py:1017
msgid "Could not initialize package manager."
msgstr "Impossible d’initialiser le gestionnaire de paquetages."

#: python/package_manager.py:1100
#, python-format
msgid "Deleting unneeded %s"
msgstr "Suppression du paquetage %s superflu"

#: python/package_manager.py:1063
msgid "Error: "
msgstr "Erreur : "

#: python/package_manager.py:966
msgid "Failed to install"
msgstr "Échec de l’installation"

#: python/package_manager.py:491 python/package_manager.py:705
msgid "Failed to lock"
msgstr "Échec du verrouillage"

#: python/package_manager.py:971
msgid "Failed to uninstall"
msgstr "Échec de la désinstallation"

#: python/package_manager.py:700 python/package_manager.py:952
msgid "Fetching failed"
msgstr "Échec de la récupération"

#: python/package_manager.py:1087
msgid "Further information regarding this error:"
msgstr "Informations complémentaires au sujet de cette erreur :"

#: python/package_manager.py:741
msgid "No such package"
msgstr "Paquetage inconnu"

#. i18n: "using it" refers to the "package manager"
#: python/package_manager.py:1077
msgid ""
"Probably another process is currently using it or the package sources are "
"corrupt. Please try again later."
msgstr ""
"Un autre processus est probablement en train de l’utiliser ou les sources "
"des paquetages sont corrompues. Veuillez réessayer ultérieurement."

#: python/package_manager.py:1074
msgid ""
"Some package conflicts could not be resolved. This was probably caused by "
"packages with \"hold\" state."
msgstr ""
"Certains conflits entre paquetages n’ont pas pu être résolus. Cela est "
"probablement dû à des paquetages en état « suspendu »."

#: python/package_manager.py:1080
msgid "The package sources are probably corrupt."
msgstr "Les sources des paquetages sont probablement corrompues."

#: python/package_manager.py:1083
msgid ""
"The sources.list entries could be repaired by executing the following "
"commands as root on this server:"
msgstr ""
"Les déclarations de sources.list peuvent être réparées en exécutant sur ce "
"serveur les commandes suivantes en tant que root :"

#: python/package_manager.py:1072
msgid "There is no free hard disk space left on the device."
msgstr "Il n’y a plus d’espace disponible sur le disque dur."

#: python/package_manager.py:871
msgid "Untrusted origin"
msgstr "Origine non fiable"

#: python/package_manager.py:1062
msgid "Warning: "
msgstr "Avertissement: "
